basic:
    name: tuhogar
    environments:
        production: 'https://www.tuhogar.com/es-co/recetas/comida-saludable/pasta-vegetariana-una-receta-rapida-y-muy-saludable'
        staging: 'https://devaem-cloud.tuhogar.com/es-co/recetas/comida-saludable/pasta-vegetariana-una-receta-rapida-y-muy-saludable'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: null
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
